### ISSUE TITLE
Problems with the environment file

### ISSUE THREAD

**Issue by jbusecke** [jbusecke/NPJCLIMATSCI-00023R1_supplementary_figure1#5]
Opened this here since @swartn noticed that he couldnt install it.

**Comment by jbusecke** [comment]
I added the specific python version used to the environment file #4. 
Could you perhaps try it again with that @swartn?
Perhaps we can specify the conda version too? That would be slightly nonsensical to me though...

**Comment by swartn** [comment]
One of the "assumptions" is that the person has a working version of Anaconda, which I think is a reasonable assumption, but we could specify in the README which versions are known to work. For me the environment setup failed with Anaconda-2.5.0, but worked with Anaconda-2.4.1 (both a bit old now, I'm not sure if you have tested with a more recent version). It might not even actually be the Anaconda version, but some permissions issue with packages partially installed by root (there are a lot of examples of this in the Anaconda issue tracker). For example, what I was hitting was:

 acrnncs@lxlp15:~/NPJCLIMATSCI-00023R1_supplementary_figure1$ conda env create -f ECSS_Paper_environment.yml
Using Anaconda Cloud api site https://api.anaconda.org
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ..........
Fetching packages ...
Error: Could not open u'/usr/local/anaconda2-2.5.0/pkgs/yaml-0.1.6-0.tar.bz2.part' for writing ([Errno 13] Permission denied: u'/usr/local/anaconda2-2.5.0/pkgs/yaml-0.1.6-0.tar.bz2.part').:  --:--:--   0.00  B/s

**Comment by swartn** [comment]
I tried on another system, with a newer version of Anaconda (4.4.0) [the most recent version], and everything worked fine. So I think this issue can be closed.
